In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [ ]:
import pandas as pd
import numpy as np

In [55]:
import os

# Current working directory ke andar sabhi files/folders list karega
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/employee-retention-data-set/Employee_data.csv

In [166]:
# Step 1: Libraries import करें
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Step 2: CSV file को read करें
file_path = '/kaggle/input/employee-retention-data-set/Employee_data.csv'
df = pd.read_csv(file_path)



# Step 4: Dataset की shape (rows, columns)

# Step 5: Columns की जानकारी और data types
print("\n Info of Dataset:")
print(df.info())

 Info of Dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74610 entries, 0 to 74609
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee ID                 74610 non-null  int64
 1   Age                         74610 non-null  int64
 2   Gender                      74610 non-null  object
 3   Years at Company            74610 non-null  int64
 4   Job Role                    74610 non-null  object
 5   Monthly Income              74610 non-null  int64
 6   Work-Life Balance           74610 non-null  object
 7   Job Satisfaction            74610 non-null  object
 8   Performance Rating          74610 non-null  object
 9   Number of Promotions        74610 non-null  int64
 10  Overtime                    74610 non-null  object
 11  Distance from Home          72698 non-null  float64
 12  Education Level             74610 non-null  object
 13  Marital Status              74610 non-null  object
 14  Number of Dependents        74610 non-null  int64
 15  Job Level                   74610 non-null  object
 16  Company Size                74610 non-null  object
 17  Company Tenure (In Months)  72197 non-null  float64
 18  Remote Work                 74610 non-null  object
 19  Leadership Opportunities    74610 non-null  object
 20  Innovation Opportunities    74610 non-null  object
 21  Company Reputation          74610 non-null  object
 22  Employee Recognition        74610 non-null  object
 23  Attrition                   74610 non-null  object
dtypes: float64(2), int64(6), object(16)
memory usage: 13.7+ MB
None

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74610 entries, 0 to 74609
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee ID                 74610 non-null  int64
 1   Age                         74610 non-null  int64
 2   Gender                      74610 non-null  object
 3   Years at Company            74610 non-null  int64
 4   Job Role                    74610 non-null  object
 5   Monthly Income              74610 non-null  int64
 6   Work-Life Balance           74610 non-null  object
 7   Job Satisfaction            74610 non-null  object
 8   Performance Rating          74610 non-null  object
 9   Number of Promotions        74610 non-null  int64
 10  Overtime                    74610 non-null  object
 11  Distance from Home          72698 non-null  float64
 12  Education Level             74610 non-null  object
 13  Marital Status              74610 non-null  object
 14  Number of Dependents        74610 non-null  int64
 15  Job Level                   74610 non-null  object
 16  Company Size                74610 non-null  object
 17  Company Tenure (In Months)  72197 non-null  float64
 18  Remote Work                 74610 non-null  object
 19  Leadership Opportunities    74610 non-null  object
 20  Innovation Opportunities    74610 non-null  object
 21  Company Reputation          74610 non-null  object
 22  Employee Recognition        74610 non-null  object
 23  Attrition                   74610 non-null  object
dtypes: float64(2), int64(6), object(16)
memory usage: 13.7+ MB

In [59]:
df.describe()

,Employee ID,Age,Years at Company,Monthly Income,Number of Promotions,Distance from Home,Number of Dependents,Company Tenure (In Months)
count,74610.000000,74610.000000,74610.000000,74610.000000,74610.000000,72698.000000,74610.000000,72197.000000
mean,37246.028696,38.529379,15.722638,7344.931417,0.832958,49.990839,1.657432,55.711899
std,21505.785344,12.082299,11.224059,2596.373589,0.995326,28.519135,1.579862,25.392325
min,1.000000,18.000000,1.000000,1226.000000,0.000000,1.000000,0.000000,2.000000
25%,18624.250000,28.000000,7.000000,5652.000000,0.000000,25.000000,0.000000,36.000000
50%,37239.500000,39.000000,13.000000,7348.500000,1.000000,50.000000,1.000000,56.000000
75%,55871.750000,49.000000,23.000000,8876.000000,2.000000,75.000000,3.000000,76.000000
max,74498.000000,59.000000,51.000000,50030.000000,4.000000,99.000000,15.000000,128.000000

In [61]:
df.head()

,Employee ID,Age,Gender,Years at Company,Job Role,Monthly Income,Work-Life Balance,Job Satisfaction,Performance Rating,Number of Promotions,...,Number of Dependents,Job Level,Company Size,Company Tenure (In Months),Remote Work,Leadership Opportunities,Innovation Opportunities,Company Reputation,Employee Recognition,Attrition
0,8410,31,Male,19,Education,5390,Excellent,Medium,Average,2,...,0,Mid,Medium,89.0,No,No,No,Excellent,Medium,Stayed
1,64756,59,Female,4,Media,5534,Poor,High,Low,3,...,3,Mid,Medium,21.0,No,No,No,Fair,Low,Stayed
2,30257,24,Female,10,Healthcare,8159,Good,High,Low,0,...,3,Mid,Medium,74.0,No,No,No,Poor,Low,Stayed
3,65791,36,Female,7,Education,3989,Good,High,High,1,...,2,Mid,Small,50.0,Yes,No,No,Good,Medium,Stayed
4,65026,56,Male,41,Education,4821,Fair,Very High,Average,0,...,0,Senior,Medium,68.0,No,No,No,Fair,Medium,Stayed

In [66]:
df.sample()

,Employee ID,Age,Gender,Years at Company,Job Role,Monthly Income,Work-Life Balance,Job Satisfaction,Performance Rating,Number of Promotions,...,Number of Dependents,Job Level,Company Size,Company Tenure (In Months),Remote Work,Leadership Opportunities,Innovation Opportunities,Company Reputation,Employee Recognition,Attrition
50408,23447,26,Male,2,Technology,7945,Good,Low,Below Average,0,...,0,Mid,Medium,34.0,No,No,Yes,Good,Medium,Stayed

In [68]:
df.shape

(74610, 24)

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74610 entries, 0 to 74609
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee ID                 74610 non-null  int64
 1   Age                         74610 non-null  int64
 2   Gender                      74610 non-null  object
 3   Years at Company            74610 non-null  int64
 4   Job Role                    74610 non-null  object
 5   Monthly Income              74610 non-null  int64
 6   Work-Life Balance           74610 non-null  object
 7   Job Satisfaction            74610 non-null  object
 8   Performance Rating          74610 non-null  object
 9   Number of Promotions        74610 non-null  int64
 10  Overtime                    74610 non-null  object
 11  Distance from Home          72698 non-null  float64
 12  Education Level             74610 non-null  object
 13  Marital Status              74610 non-null  object
 14  Number of Dependents        74610 non-null  int64
 15  Job Level                   74610 non-null  object
 16  Company Size                74610 non-null  object
 17  Company Tenure (In Months)  72197 non-null  float64
 18  Remote Work                 74610 non-null  object
 19  Leadership Opportunities    74610 non-null  object
 20  Innovation Opportunities    74610 non-null  object
 21  Company Reputation          74610 non-null  object
 22  Employee Recognition        74610 non-null  object
 23  Attrition                   74610 non-null  object
dtypes: float64(2), int64(6), object(16)
memory usage: 13.7+ MB

In [74]:
df.loc()

In [76]:
df.iloc[0:2,0:5]

   Employee ID  Age  Gender  Years at Company   Job Role
0         8410   31    Male                19  Education
1        64756   59  Female                 4      Media

In [78]:
df.loc[0]

Employee ID                               8410
Age                                         31
Gender                                    Male
Years at Company                            19
Job Role                             Education
Monthly Income                            5390
Work-Life Balance                    Excellent
Job Satisfaction                        Medium
Performance Rating                     Average
Number of Promotions                         2
Overtime                                    No
Distance from Home                        22.0
Education Level               Associate Degree
Marital Status                         Married
Number of Dependents                         0
Job Level                                  Mid
Company Size                            Medium
Company Tenure (In Months)                89.0
Remote Work                                 No
Leadership Opportunities                    No
Innovation Opportunities                    No
Company Reputation                   Excellent
Employee Recognition                    Medium
Attrition                               Stayed
Name: 0, dtype: object

In [79]:
df.iloc[0,0]

8410

In [80]:
df.isnull()

,Employee ID,Age,Gender,Years at Company,Job Role,Monthly Income,Work-Life Balance,Job Satisfaction,Performance Rating,Number of Promotions,...,Number of Dependents,Job Level,Company Size,Company Tenure (In Months),Remote Work,Leadership Opportunities,Innovation Opportunities,Company Reputation,Employee Recognition,Attrition
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74605,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
74606,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
74607,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
74608,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
74609,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [81]:
df.notnull()

,Employee ID,Age,Gender,Years at Company,Job Role,Monthly Income,Work-Life Balance,Job Satisfaction,Performance Rating,Number of Promotions,...,Number of Dependents,Job Level,Company Size,Company Tenure (In Months),Remote Work,Leadership Opportunities,Innovation Opportunities,Company Reputation,Employee Recognition,Attrition
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74605,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
74606,True,True,True,True,True,True,True,True,True,True,...,True,True,True,False,True,True,True,True,True,True
74607,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
74608,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
74609,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [82]:
df.dropna()

,Employee ID,Age,Gender,Years at Company,Job Role,Monthly Income,Work-Life Balance,Job Satisfaction,Performance Rating,Number of Promotions,...,Number of Dependents,Job Level,Company Size,Company Tenure (In Months),Remote Work,Leadership Opportunities,Innovation Opportunities,Company Reputation,Employee Recognition,Attrition
0,8410,31,Male,19,Education,5390,Excellent,Medium,Average,2,...,0,Mid,Medium,89.0,No,No,No,Excellent,Medium,Stayed
1,64756,59,Female,4,Media,5534,Poor,High,Low,3,...,3,Mid,Medium,21.0,No,No,No,Fair,Low,Stayed
2,30257,24,Female,10,Healthcare,8159,Good,High,Low,0,...,3,Mid,Medium,74.0,No,No,No,Poor,Low,Stayed
3,65791,36,Female,7,Education,3989,Good,High,High,1,...,2,Mid,Small,50.0,Yes,No,No,Good,Medium,Stayed
4,65026,56,Male,41,Education,4821,Fair,Very High,Average,0,...,0,Senior,Medium,68.0,No,No,No,Fair,Medium,Stayed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74604,11030,57,Male,12,Technology,8438,Excellent,Medium,High,0,...,2,Mid,Medium,27.0,No,No,Yes,Good,Medium,Stayed
74605,13450,44,Female,20,Healthcare,7578,Fair,Medium,Low,2,...,3,Mid,Large,52.0,No,No,No,Fair,Very High,Left
74607,36968,28,Female,3,Technology,9763,Poor,Low,Average,0,...,3,Senior,Small,67.0,No,No,No,Poor,Medium,Left
74608,24276,37,Male,3,Education,3644,Fair,High,Average,2,...,4,Entry,Medium,16.0,No,No,No,Excellent,Medium,Stayed
74609,9839,38,Male,28,Media,6172,Good,High,High,0,...,2,Mid,Medium,84.0,No,No,No,Excellent,Low,Stayed

In [160]:
import pandas as pd
df['Monthly Income'].mean()

7344.931416700174

In [161]:
df['Monthly Income'].mode()

0    50030
Name: Monthly Income, dtype: int64

In [89]:
# Missing values की count
df.isnull().sum()

Employee ID                      0
Age                              0
Gender                           0
Years at Company                 0
Job Role                         0
Monthly Income                   0
Work-Life Balance                0
Job Satisfaction                 0
Performance Rating               0
Number of Promotions             0
Overtime                         0
Distance from Home            1912
Education Level                  0
Marital Status                   0
Number of Dependents             0
Job Level                        0
Company Size                     0
Company Tenure (In Months)    2413
Remote Work                      0
Leadership Opportunities         0
Innovation Opportunities         0
Company Reputation               0
Employee Recognition             0
Attrition                        0
dtype: int64

In [90]:
df.nunique()

Employee ID                   74498
Age                              42
Gender                            2
Years at Company                 51
Job Role                          5
Monthly Income                 9836
Work-Life Balance                 4
Job Satisfaction                  4
Performance Rating                4
Number of Promotions              5
Overtime                          2
Distance from Home               99
Education Level                   5
Marital Status                    3
Number of Dependents              9
Job Level                         3
Company Size                      3
Company Tenure (In Months)      127
Remote Work                       2
Leadership Opportunities          2
Innovation Opportunities          2
Company Reputation                4
Employee Recognition              4
Attrition                         2
dtype: int64

In [94]:
import pandas as pd
mean_income = df['Monthly Income'].mean()
print("Mean of Monthly Income:", mean_income)

Mean of Monthly Income: 7344.931416700174

In [95]:
import pandas as pd
mode_income = df['Monthly Income'].mode()
print("Mode of Monthly Income:", mode_income)

Mode of Monthly Income: 0    50030
Name: Monthly Income, dtype: int64

In [100]:
from sklearn.model_selection import train_test_split

# Step 1: Define feature matrix X and target variable y
# (Replace 'Attrition' with your actual target column if different)
X = df.drop('Attrition', axis=1)
y = df['Attrition']


X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("✅ Train and Validation Split Complete")
print(" X_train shape:", X_train.shape)
print(" X_val shape:", X_val.shape)
print(" y_train shape:", y_train.shape)
print(" y_val shape:", y_val.shape)

✅ Train and Validation Split Complete
 X_train shape: (59688, 23)
 X_val shape: (14922, 23)
 y_train shape: (59688,)
 y_val shape: (14922,)

In [99]:
print(" Categorical Summary:")
print(train_df.describe(include='object'))

 Categorical Summary:
       Attrition
count      59598
unique         2
top       Stayed
freq       31302

In [102]:
# Missing values count
print(" Missing Values:")
print(train_df.isnull().sum())

 Missing Values:
Employee ID                      0
Age                              0
Years at Company                 0
Monthly Income                   0
Number of Promotions             0
Distance from Home            1530
Number of Dependents             0
Company Tenure (In Months)    1877
Attrition                        0
dtype: int64

In [103]:
df.describe()

,Employee ID,Age,Years at Company,Monthly Income,Number of Promotions,Distance from Home,Number of Dependents,Company Tenure (In Months)
count,74610.000000,74610.000000,74610.000000,74610.000000,74610.000000,72698.000000,74610.000000,72197.000000
mean,37246.028696,38.529379,15.722638,7344.931417,0.832958,49.990839,1.657432,55.711899
std,21505.785344,12.082299,11.224059,2596.373589,0.995326,28.519135,1.579862,25.392325
min,1.000000,18.000000,1.000000,1226.000000,0.000000,1.000000,0.000000,2.000000
25%,18624.250000,28.000000,7.000000,5652.000000,0.000000,25.000000,0.000000,36.000000
50%,37239.500000,39.000000,13.000000,7348.500000,1.000000,50.000000,1.000000,56.000000
75%,55871.750000,49.000000,23.000000,8876.000000,2.000000,75.000000,3.000000,76.000000
max,74498.000000,59.000000,51.000000,50030.000000,4.000000,99.000000,15.000000,128.000000

In [112]:
print("✅ Final Processed DataFrame Shape:", df.shape)
print(" Columns:\n", df.columns)

✅ Final Processed DataFrame Shape: (74610, 24)
 Columns:
 Index(['Employee ID', 'Age', 'Gender', 'Years at Company', 'Job Role',
       'Monthly Income', 'Work-Life Balance', 'Job Satisfaction',
       'Performance Rating', 'Number of Promotions', 'Overtime',
       'Distance from Home', 'Education Level', 'Marital Status',
       'Number of Dependents', 'Job Level', 'Company Size',
       'Company Tenure (In Months)', 'Remote Work', 'Leadership Opportunities',
       'Innovation Opportunities', 'Company Reputation',
       'Employee Recognition', 'Attrition'],
      dtype='object')

In [122]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [130]:
# Attrition को 0 और 1 में encode करना (Yes/No से अगर है तो)
df['Attrition'] = df['Attrition'].map({'Yes': 1, 'No': 0})

In [134]:
# Automatically detect and encode all categorical columns
cat_cols = df.select_dtypes(include='object').columns
df = pd.get_dummies(df, columns=cat_cols, drop_first=True)

In [138]:
Prediction and Model Evaluation
from sklearn.preprocessing import StandardScaler

# Features ko scale karna (StandardScaler ka use)
scaler = StandardScaler()
X_train = scaler.fit_transform(Age)
X_test = scaler.transform(overtime)

SyntaxError: invalid syntax (2260113574.py, line 1)

In [151]:

X_train['Gender'] = X_train['Gender'].map({'Male': 1, 'Female': 0})
X_test['Gender'] = X_test['Gender'].map({'Male': 1, 'Female': 0})

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

,Employee ID,Age,Gender,Years at Company,Job Role,Monthly Income,Work-Life Balance,Job Satisfaction,Performance Rating,Number of Promotions,...,Marital Status,Number of Dependents,Job Level,Company Size,Company Tenure (In Months),Remote Work,Leadership Opportunities,Innovation Opportunities,Company Reputation,Employee Recognition
41130,71946,43,NaN,28,Media,5924,Fair,High,High,0,...,Divorced,1,Senior,Medium,78.0,No,No,No,Good,Low
26494,18696,58,NaN,48,Technology,8527,Fair,High,High,0,...,Single,2,Senior,Medium,111.0,No,No,No,Fair,High
29194,42951,49,NaN,40,Finance,10567,Good,High,Low,1,...,Married,0,Mid,Medium,89.0,No,No,Yes,Good,High
33620,21664,53,NaN,16,Technology,10691,Fair,High,Average,0,...,Divorced,0,Entry,Small,81.0,No,No,No,Good,High
12529,12052,22,NaN,5,Healthcare,8343,Good,High,High,0,...,Single,3,Mid,Small,27.0,No,No,Yes,Poor,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69557,24255,31,NaN,16,Technology,7431,Fair,Low,Low,0,...,Married,2,Mid,Medium,74.0,Yes,No,Yes,Good,High
56869,61517,51,NaN,32,Healthcare,6702,Good,High,Average,2,...,Single,2,Mid,Large,98.0,Yes,No,No,Excellent,Low
65214,62179,51,NaN,37,Healthcare,7527,Excellent,Very High,Average,0,...,Single,3,Senior,Large,97.0,No,No,No,Good,Medium
61694,53128,24,NaN,4,Education,4243,Fair,High,Average,3,...,Married,2,Mid,Medium,22.0,No,No,No,Good,Low
6751,59616,47,NaN,23,Healthcare,7240,Fair,Medium,Average,0,...,Single,3,Entry,Medium,87.0,Yes,No,Yes,Good,Medium